name: bazel

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: bazelisk test ...
      working-directory: test
    - run: bazelisk test ... --@boost.asio//:ssl=boringssl
      working-directory: test
